# Generated by Django 2.0.5 on 2018-05-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerypage',
            name='galery_type',
            field=models.CharField(choices=[('GRID', 'Grid'), ('COMP', 'Compact'), ('CARD', 'Card')], default='GRID', max_length=4),
        ),
    ]
