# Generated by Django 2.0.5 on 2018-05-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180515_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='subtitle',
            field=models.CharField(default='', help_text='Write a subtitle for the page', max_length=255),
            preserve_default=False,
        ),
    ]
