# Generated by Django 2.0.5 on 2018-05-17 13:19

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180517_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardpage',
            name='body',
            field=wagtail.core.fields.StreamField((('heading', wagtail.core.blocks.CharBlock(classname='full title', required=False)), ('paragraph', wagtail.core.blocks.RichTextBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))), blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Write a subtitle for the page', max_length=255, null=True),
        ),
    ]
