# Generated by Django 2.0.5 on 2018-05-18 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('home', '0005_auto_20180517_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='featured_gallery',
            field=models.ForeignKey(blank=True, help_text='Gallery section.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Gallery section at homepage'),
        ),
    ]
