# Generated by Django 2.0.5 on 2018-05-21 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('home', '0006_homepage_featured_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='featured_location',
            field=models.ForeignKey(blank=True, help_text='Location section.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Featured location page at homepage'),
        ),
    ]
