# Generated by Django 2.0.5 on 2018-05-22 14:09

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20180522_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(help_text='Telephone number. Ex.: +1-877-296-1018', max_length=20)),
                ('contact_type', models.CharField(choices=[('CS', 'Customer Service'), ('TS', 'technical support'), ('BS', 'billing support'), ('BP', 'bill payment'), ('S', 'sales'), ('R', 'reservations'), ('CC', 'credit card support'), ('E', 'emergency'), ('BT', 'baggage tracking'), ('RA', 'roadside assistance'), ('PT', 'package tracking')], default='GRID', max_length=2)),
                ('area_served', models.CharField(blank=True, help_text='The geographical region served by the number, specified as a AdministrativeArea. Countries may be specified concisely using just their standard ISO-3166 two-letter code, as in the examples below. If omitted, the number is assumed to be global. Examples: "US", "GB", ["US","CA","MX"]', max_length=2, null=True)),
                ('available_language', models.CharField(blank=True, help_text='Details about the language spoken. Languages may be specified by their common English name. If omitted, the language defaults to English. Examples: "English", "Spanish", ["French","English"]', max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Social networks',
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='contact_points',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='home.ContactNumbers'),
        ),
    ]
