# Generated by Django 2.0.5 on 2018-05-22 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20180522_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactnumbers',
            options={'verbose_name_plural': 'Contact Points'},
        ),
    ]
