# Generated by Django 2.0.5 on 2018-05-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20180522_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='contact_points',
            field=models.ManyToManyField(blank=True, to='home.ContactNumbers'),
        ),
    ]
