# Generated by Django 2.0.5 on 2018-05-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20180522_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactnumbers',
            name='contact_type',
            field=models.CharField(choices=[('CS', 'customer service'), ('TS', 'technical support'), ('BS', 'billing support'), ('BP', 'bill payment'), ('S', 'sales'), ('R', 'reservations'), ('CC', 'credit card support'), ('E', 'emergency'), ('BT', 'baggage tracking'), ('RA', 'roadside assistance'), ('PT', 'package tracking')], default='GRID', max_length=2),
        ),
    ]
