# Generated by Django 2.0.5 on 2018-05-22 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('home', '0012_auto_20180522_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ForeignKey(blank=True, help_text="Image Google Search uses for your organization's logo in Search results and in the Knowledge Graph. Size: 112x112px at minimum. Must be in .jpg, .png, or. gif format", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
