# Generated by Django 2.0.5 on 2018-05-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_organization_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_cta',
            field=models.CharField(blank=True, help_text='Text to display on Call to Action', max_length=255, null=True, verbose_name='Hero Call To Action'),
        ),
    ]
