# Generated by Django 2.0.5 on 2018-05-24 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20180524_1807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactnumbers',
            options={'verbose_name': 'Contact Point', 'verbose_name_plural': 'Contact Points'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AlterModelOptions(
            name='socialprofiles',
            options={'verbose_name': 'Social Profile', 'verbose_name_plural': 'Social networks'},
        ),
        migrations.AlterField(
            model_name='homepage',
            name='featured_section_1',
            field=models.ForeignKey(blank=True, help_text='First featured section for the homepage. Will display up to three child items', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Featured section 1'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.TextField(blank=True, help_text='Comma separated list with the following format:<street address>,<address locality (city)>, <address region>,<postal code>,<address country (two letters)>. Ex.: 1901 Lemur Ave, Sunnyvale, CA, 94086, US ', null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, help_text='From the business ', null=True),
        ),
        migrations.AlterField(
            model_name='socialprofiles',
            name='name',
            field=models.CharField(help_text='Name of the social network', max_length=255, verbose_name='name'),
        ),
    ]
