# Generated by Django 2.0.5 on 2018-05-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20180524_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='list_child_pages',
            field=models.BooleanField(default=False),
        ),
    ]
