# Generated by Django 2.0.5 on 2018-05-17 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0004_auto_20180517_0440'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturesIndexPage',
            fields=[
                ('standardpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.StandardPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('home.standardpage',),
        ),
        migrations.CreateModel(
            name='FeaturesPage',
            fields=[
                ('standardpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.StandardPage')),
                ('icon', models.TextField(blank=True, help_text='FontAwesome icon to describe the service e.g.: fa-facebook Full list at: https://fontawesome.com/v4.7.0/icons/')),
            ],
            options={
                'abstract': False,
            },
            bases=('home.standardpage',),
        ),
    ]
